docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - { Intro: intro.md }
    - { 'Basic Usage': usage.md }
    - { Reference: [{ Laminas\Json\Server\Server: server.md }, { Laminas\Json\Server\Request: request.md }, { Laminas\Json\Server\Response: response.md }, { Laminas\Json\Server\Error: error.md }, { 'Service Mapping Description (SMD)': smd.md }] }
site_name: laminas-json-server
site_description: Laminas\Json\Server
repo_url: 'https://github.com/laminas/laminas-json-server'
extra:
    project: Components
    project_url: 'https://docs.laminas.dev'
